server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/noname29-sparta/Backend
          search-paths: config-file/**
          default-label: delivery

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true