spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: changda-eun
    password: 10041004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 19095